### PR TITLE
Fix the TypeScript types

### LINKED ISSUE #184: broken types for `parse`
by adding `|number` to the value side of ParsedQuery, you've changed the return type in a really breaking the type signature for users who don't use `parseNumbers` - now every use of this generates errors like this:
```
[devserver] TS2345: Argument of type 'string | number | ReactText[]' is not assignable to parameter of type 'string | string[]'.
[devserver]   Type 'number' is not assignable to type 'string | string[]'.
```
This is only going to get worse when #183 is fixed.

I'd like to suggest either a complex typescript signature such that only passing `parseNumbers` results in the new `string |number| (number|string)[]`, or introduce a new  function `parseValues` which does the number/boolean/etc

### PR DESCRIPTION
**Pull request by cdeutsch**
We need to return different versions of `ParsedQuery` based on the values of `parseBooleans` and `parseNumbers`.

Not sure about the naming. A bit verbose, but....

Fixes #184

@alecf @felixoi will this work for you?

### CODE REVIEW

**Comment by cdeutsch** [comment]
Note I also removed the `readonly` from `ParsedQuery` and its variants, because `parse` is not returning a readonly object. You are able to modify its results (and I do in my code). Maybe I'm missing something there?

File: index.d.ts [hunk 1]
```diff
@@ -90,7 +90,19 @@ export interface ParseOptions {
 }
 
 export interface ParsedQuery {
-	readonly [key: string]: string | number | boolean | Array<string | number | boolean> | null | undefined;
+	[key: string]: string | Array<string> | null | undefined;
```
Comment (alecf) [inline index.d.ts]: you could possibly simplify this as

```typescript
export interface ParseQuery<T> {
  [key: string]: T | Array<T> | null | undefined;
}
```

and then you can just use:

```typescript
export function parse(query: string, options: { parseBooleans: true, parseNumbers: true } & ParseOptions): ParsedQuery<string | number | boolean>;
```

etc..

Comment (cdeutsch) [reply index.d.ts]: Good call. I'll change it to that

Comment (cdeutsch) [reply index.d.ts]: Updated. Thanks! 👍

**Comment by cdeutsch** [comment]
Oops. Accidentally deleted the branch from my repo when cleaning up.
